version: '3'

services:
  worker:
    build: 
      context: .
      dockerfile: worker/Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend
  backend:
    build: app
    volumes:
      - ./app:/app
    ports:
      - 6000:5000
    environment:
      FLASK_ENV: development
    depends_on:
      - rabbitmq
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '15672:15672'